### ISSUE TITLE
Change Email

### ISSUE THREAD

**Issue by latgit** [sariaRiski02/AksaraDiskret#10]
Can't change email in admin

**Comment by sariaRiski02** [comment]
ok i'wil check that

**Comment by sariaRiski02** [comment]
it's been going well. and I think the code is better.

**Comment by latgit** [comment]
ok i will test it again

**Comment by latgit** [comment]
Ok i will test it again

**Comment by sariaRiski02** [comment]
i guest you must checking when users/admin close the browser and then users use feature setting if still work
