### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by latgit** [sariaRiski02/AksaraDiskret#14]

**Comment by sariaRiski02** [comment]
what do you mean? should we add this feature?

**Comment by latgit** [comment]
Just a common feature that is in the login system. Maybe if it can be added even better

**Comment by sariaRiski02** [comment]
i will try to add it. maybe 1 or 2 days. because I have college assignments to complete

**Comment by sariaRiski02** [comment]
mybe i cant continue this feature cause im making IMK assignment
