### ISSUE TITLE
Cookie is broken again

### ISSUE THREAD

**Issue by latgit** [sariaRiski02/AksaraDiskret#16]
1. When signin with "users" and check the "Remember Me".
2. When signin with "admin" and check the "Remember Me". Then go to admin page, it's asked to signin.

**Comment by sariaRiski02** [comment]
i guest we discusion for this problem. this has something to do with cookies in the settings

**Comment by sariaRiski02** [comment]
this happens because the cookie time has expired. but I have solved this problem. and I think the cookies you provided are too short

**Comment by sariaRiski02** [comment]
this problem fixed you can remove this issue
