### ISSUE TITLE
Page Access

### ISSUE THREAD

**Issue by latgit** [sariaRiski02/AksaraDiskret#7]
When the "users" (not admin) is signed in, it should not be able to access again to the signup & signin page.

**Comment by sariaRiski02** [comment]
this problem has been resolved

**Comment by latgit** [comment]
Why? are there any more problems?

**Comment by sariaRiski02** [comment]
no, all went well

**Comment by latgit** [comment]
Okay. if there is no problem I will close it. Thank You
