### ISSUE TITLE
The user "Name" changes to "Admin" when the browser is closed

### ISSUE THREAD

**Issue by latgit** [sariaRiski02/AksaraDiskret#8]
**Steps to reproduce :**

1. Sign in with users & check "Remember Me".
2. Close the browser & open immediately.
3. Open "Books collection" page.

**Comment by sariaRiski02** [comment]
I fixed it but I haven't pushed it to github yet

Pada tanggal Sab, 20 Mei 2023 19.45, Rezky Wahyudi M. <
***@***.***> menulis:

**Comment by latgit** [comment]
Why? are there any more problems?

**Comment by sariaRiski02** [comment]
i write this message 3 days ago boss... wkwkw.  this problem is solved

**Comment by latgit** [comment]
[sariaRiski02](https://github.com/sariaRiski02) reopened this [9 hours ago](https://github.com/sariaRiski02/AksaraDiskret/issues/8#event-9305326831) LOL
